version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: gopher_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres 
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_messages=info
      -c shared_preload_libraries=pg_stat_statements

volumes:
  postgres_data:
    driver: local