// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	Product   string    `gorm:"column:product;type:character varying(100);not null" json:"product"`
	Quantity  int32     `gorm:"column:quantity;type:integer;not null;default:1" json:"quantity"`
	Price     float64   `gorm:"column:price;type:numeric(10,2);not null" json:"price"`
	Status    string    `gorm:"column:status;type:character varying(20);default:pending" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
